In [1]:
# import needed packages
import numpy as np
import simulation_argument_model.model_code.utilities_visuals as ut
import simulation_argument_model.model_code.utilities_simulation as us
import simulation_argument_model.model_code.ArgModel as normal_am
import simulation_argument_model.model_code.reducedArgModel as reduced_am

In [2]:
M = 4
# defines the parameters needed to run the model
model_parameters = {
    "no_of_agents": 100
    , "no_of_iterations": 16000
    # strength of biased processing
    , "ß": 3.2
    # number of implicitly modelled arguments
    , "M": M
    # linkage matrix
    , "C": us.create_connection_matrix_symmetrical(no_of_arguments=M, normalised=True)
    # initiation of agents attitude
    , "initiation": "binomial"
}

SPA_param = {
    'params_to_iter': np.array(['ß', 'M', 'no_of_agents']),
    'sims_per_comb': 10,
    'boundaries': np.array([[0,6], [4,64], [100,100]]),
    'no_of_steps': np.array([3, 3, 1])
}

In [ ]:
measures = {
    #"time_until_consens": model_parameters["no_of_iterations"],
    #, "mean_attitude_END_VALUE": 0
    "variance_attitude": np.zeros(model_parameters["no_of_iterations"])
}

measures_from_SPA_normal = normal_am.systematic_parameter_analysis(SPA_param, model_parameters, measures)

ut.pickle_sim(measures_from_SPA_normal, SPA_param)
#%store measures_from_SPA_normal

[  0.   4. 100.]
[  0.  34. 100.]
[  0.  64. 100.]


In [9]:
measures = {
    #"time_until_consens": model_parameters["no_of_iterations"],
    #, "mean_attitude_END_VALUE": 0
    #, "variance_attitude_END_VALUE": 0
    "variance_attitude": np.zeros(model_parameters["no_of_iterations"])
}
measures_from_SPA_reduced = reduced_am.systematic_parameter_analysis(SPA_param, model_parameters, measures)

ut.pickle_sim(measures_from_SPA_reduced, SPA_param)

NameError: name 'model_parameters' is not defined

In [3]:
measures_from_SPA_normal = ut.load_sim_from_name("NormalModel_binomial_N100_100_M4_64_T16000_S100_ß0_6.p")

In [3]:
measures_from_SPA_normal = ut.load_sim(model_parameters, SPA_param, "NormalModel")
measures_from_SPA_reduced = ut.load_sim(model_parameters, SPA_param, "ReducedModel")

In [5]:
def filter_for(SPA_data, param_tuples):
    SPA_data_filtered = []
    for sim in SPA_data:
        for param, value in param_tuples:
            if sim[param] == value:
                SPA_data_filtered.append(sim)

    return SPA_data_filtered

measures_from_SPA_normal = filter_for(measures_from_SPA_normal, [("no_of_agents", 1000)])
measures_from_SPA_reduced = filter_for(measures_from_SPA_reduced, [("no_of_agents", 1000)])

In [ ]:
ut.xy_plot_measurement_boxplot('ß', 'time_until_consens', measures_from_SPA_normal)

In [ ]:
ut.xy_plot_measurement_boxplot('ß', 'time_until_consens', measures_from_SPA_reduced)

In [ ]:
ut.plot_beta_against_time_until_consens_two_sims(measures_from_SPA_normal, measures_from_SPA_reduced, 1000, "low_beta")

In [ ]:
ut.variance_consensusrate_against_beta(measures_from_SPA_reduced, 1000)

In [ ]:
ut.consensrate_withrespect_T_against_beta(measures_from_SPA_reduced, [1000, 2000, 4000, 8000, 16000, 32000])

In [ ]:
ut.convergence_time_against_beta(measures_from_SPA_normal, measures_from_SPA_reduced)

In [4]:
ut.consensrate_withrespect_M_against_beta(measures_from_SPA_normal, [4,34,64], 1000)

In [5]:
ut.consensrate_withrespect_M_against_beta(measures_from_SPA_reduced, [4,34,64], 1000)